dist: trusty
sudo: required

language: node_js

cache:
  directories:
  - node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

node_js:
  - "4"
  - "6"
  - "7"
