language: node_js

dist: trusty

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

cache:
  directories:
  - node_modules

node_js:
  - "4"
  - "6"
  - "7"
